FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json turbo.json .npmrc ./


COPY apps/frontend/package.json apps/frontend/
COPY packages/db/package.json packages/db/

RUN npm install

COPY apps/frontend apps/frontend/
COPY packages/db packages/db/


RUN npm run generate:db

EXPOSE 5173

CMD ["npm", "run" , "start:frontend"]
