name: CI/CD Pipeline for KnightsChess ws

on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.ws
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/knightschess-ws:latest

      # Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/knightschess-ws:latest
            
            # Stop and remove existing container (if running)
            docker stop ws || true
            docker rm ws || true
            
            # Run the new container
            docker run -d --name ws -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/knightschess-ws:latest
            
            # Clean up unused images
            docker image prune -f